# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Design System
email: johnson_koh@tech.gov.sg
description: >- # this means to ignore newlines until "baseurl:"
  Design System unites Singapore Government digital services around a common visual language and user experience
baseurl: "" # the s.sgdsath of your site, e.g. /blog
url: "https://designsystem.gov.sg" # the base hostname & protocol for your site, e.g. http://example.com
sgds-version: 1.2.1
twitter_username: jekyllrb
github_username:  jekyll
last_updated: 23 April 2019
contact_us: 'https://form.gov.sg/forms/govtech/5bc440ac507956000fdbae91'
feedback_form: 'https://form.gov.sg/#!/forms/govtech/5bd12c6668dbe7000fff9ace'
search_placeholder: 'What are you looking for?'
# Build settings
markdown: kramdown
plugins:
  - jekyll-assets
  - jekyll-seo-tag

breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text

assets:
  source_maps: true
  sources:
    - fonts
  digest: true

sass:
  load_paths:
  - sgds-govtech

includes:
  # - contents/docs

exclude:
  - .idea
  - .vscode
  - node_modules
  - scripts
  - src
  - Dockerfile
  - Gemfile*
  - package*.json
  - README.md
  - webpack.config.js
  - Gruntfile.js
  - amplify.yml
