# For Jekyll SEO
title: Singapore Government Design System
description: >-
  Design System unites Singapore Government digital services around a common visual language 
  and user experience
logo: /assets/img/logo_sgds.png

# Site data
sgds-version: 1.3.20
report-vulnerability: "https://tech.gov.sg/report_vulnerability"
contact-us: "https://form.gov.sg/forms/govtech/5bc440ac507956000fdbae91"
feedback-form: "https://form.gov.sg/#!/forms/govtech/5bd12c6668dbe7000fff9ace"
request-component: "nolink"
search_placeholder: "What are you looking for?"

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from

collections_dir: collections
collections:
  standard:
    permalink: /docs/:path/
    output: true
    order: 1
    cat: components
  layout:
    permalink: /docs/:path/
    output: true
    order: 2
    cat: components
  general:
    permalink: /docs/:path/
    output: true
    order: 3
    cat: components
  form:
    permalink: /docs/:path/
    output: true
    order: 4
    cat: components
  helpers:
    permalink: /docs/:path/
    output: true
    order: 5
    cat: components
  guides:
    permalink: /guides/:path/
    output: true
    cat: guides
  patterns:
    permalink: /patterns/:path/
    output: true
    cat: patterns
  default-templates:
    permalink: /templates/:path/
    output: true
    cat: templates

exclude:
  - apps/src
  - node_modules
  - build
  - scripts
  - Dockerfile
  - Gemfile*
  - package*.json
  - README.md
  - webpack.config.js
  - Gruntfile.js
  - amplify.yml

sass:
  sass_dir: assets/custom-css
